### ISSUE TITLE
Usage documentation with angular CLI

### ISSUE THREAD

**Issue by julienboulay** [realappie/ngx-translate-merge#8]
Hi @realappie,

Thank you for this great work. Could you please give more information about how to use this module with angular CLI and how to configure ngx-translate to use the single i18n bundle ?
Thanks

**Comment by abdel-ships-it** [comment]
@julienboulay Thanks Julien, this tool is actually intended to be used primarily for [ngx-translate](https://github.com/ngx-translate) json files. So it technically has nothing to do with the `angular-cli`, I also don't understand what you mean by 'single i18n bundle' could you explain ? 😊

**Comment by julienboulay** [comment]
I understand that this tools allows to merge json files into one single json file for ngx-translate.
If I'm using angular-cli with `ng serve` and if one of the json files is updated, how to update the single json file ? Do I need to run ngx-translate-merge on my own, with a watcher on i18n directory ?

**Comment by abdel-ships-it** [comment]
Yeah you would have to do that indeed, although you have a very legit case. Let me know how you plan to implement it, you could try contributing to the project as I sadly don't have time to implement this :/ Thanks a lot for considering to use `ngx-translate-merge` regardless man👍
